spring:
  profiles:
    active: dev
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
#      datasource:
#        #流控规则
#        flow:
#          nacos:
#            server-addr: localhost:8848
#            username: nacos
#            password: nacos
#            group-id: sentinel
#            rule-type: flow
#            data-id: content-service-flow-rules
#            data-type: json
#        degrade:
#          #熔断规则
#          nacos:
#            server-addr: localhost:8848
#            username: nacos
#            password: nacos
#            group-id: sentinel
#            rule-type: degrade
#            data-id: content-service-degrade-rules
#            data-type: json

feign:
  sentinel:
    enabled: true





